- css/style.css
- js/script.js
loading image is another one in nextcloud.
strange behaviour when files.app was reinitialized, so i decided to reload the whole interface with OC.reload()
> minor fixes

- lib/AppInfo/Application.php
- lib/Command/CompleteOCR.php
- lib/Controller/Errors.php
- lib/Controller/OcrController.php
- lib/Db/OcrStatusMapper.php
- lib/Service/GearmanWorkerService.php
- lib/Service/OcrService.php
- worker/GearmanOCRWorker.php
@janis91 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/janis91/ocr/
> Scrutinizer Auto-Fixes

- .scrutinizer.yml
- CHANGELOG.md
- README.md
- js/ocrapp.js
- js/ocrocr.js
- js/ocrview.js
- lib/AppInfo/Application.php
- lib/Command/CompleteOCR.php
- lib/Service/GearmanWorkerService.php
- lib/Service/OcrService.php
- worker/GearmanOCRWorker.php
added the translation strings and fixed them.
> prepared translation strings

- CHANGELOG.md
- README.md
- appinfo/database.xml
- appinfo/info.xml
- lib/Service/GearmanWorkerService.php
- lib/Service/OcrService.php
- tests/AppInfo/ApplicationTest.php
- tests/Command/CompleteOCRTest.php
- tests/Controller/OcrControllerTest.php
- tests/Db/MapperTestUtility.php
- tests/Db/OcrStatusMapperTest.php
- tests/Db/OcrStatusTest.php
- tests/Service/GearmanWorkerServiceTest.php
- tests/Service/OcrServiceTest.php
- tests/TestCase.php
some things were not required and already covered by other methods -> removed these lines; added many tests for better test coverage.
#9 
Better test coverage.
> added tests and quickfixes

- CHANGELOG.md
- README.md
- appinfo/info.xml
- js/ocrview.js
Small bugfix for view according to #19
> small bugfix

- .travis.yml
the nextcloud/server master branch sometimes fails. So I switched the target branch to stable10, which is basically the target of ocr.
none
solve build ci problem.
travis
> update travis to stable10 branch

- .travis.yml
- travis_ci/before_install.sh
> Travis.yml update for mysql

- .travis.yml
- travis_ci/before_install.sh
> Update for mysql

- .travis.yml
- CHANGELOG.md
- README.md
- appinfo/info.xml
> update to php 7.1

- lib/Service/OcrService.php
made some changes in the list-language function in order to recognize all languages and list them alphabetically.
#37 
Not all languages have been regonized before.
dev environment.
> now lists the languages correctly and alphabetically

- js/ocrapp.js
- tests/Db/MapperTestUtility.php
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix typos in comments (found by codespell)

- lib/Service/QueueService.php
> 69: Fixed a typo in translation text

- .travis.yml
- lib/Service/OcrService.php
Also adjusted the code coverage send behaviour for travis.
#63 and #64
> 63: Fix endless loop behaviour

- README.md
- appinfo/info.xml
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix some typos

- lib/Service/OcrService.php
In order to see what the results from the tesseract list-langs command are.
#61
> 61: Added a debug point

- .scrutinizer.yml
- lib/Service/QueueService.php
Also changed the scrutinizer timeout to 10 minutes like in #77 requested.
#59
> 59: Added a handler for not available message queueing

- tests/Unit/phpunit.xml
> 77: Fix code coverage

- lib/Util/PHPUtil.php
As per https://github.com/tesseract-ocr/
> Spelling: Tesseract

- templates/settings-admin.php
As per https://www.docker.com and https://github.com/
> Spelling: Docker, GitHub

- CHANGELOG.md
- appinfo/info.xml
- js/dist/ocradmin.js
- js/dist/ocrapp.js
- js/src/admin/controller/controller.spec.ts
- js/src/admin/controller/controller.ts
- js/src/admin/service/http.service.spec.ts
- js/src/admin/service/http.service.ts
- js/src/app/controller/controller.ts
- lib/AppInfo/Application.php
- lib/Constants/OcrConstants.php
- lib/Controller/AdminSettingsController.php
- lib/Service/AppConfigService.php
- lib/Settings/Admin.php
- lib/Util/RedisUtil.php
- redis/Dockerfile
- redis/redis.conf
- templates/settings-admin.php
- tests/Unit/Controller/AdminSettingsControllerTest.php
- tests/Unit/Service/AppConfigServiceTest.php
- tests/Unit/Settings/AdminTest.php
- worker/Dockerfile
- worker/package.json
- worker/src/configuration/worker.configuration.ts
> 102: Added Redis AUTH

- appinfo/app.php
- js/dist/ocradmin.js
- js/dist/ocrapp.js
- js/dist/ocrpersonal.js
- js/src/admin/controller/controller.spec.ts
- js/src/admin/controller/controller.ts
- js/src/app/view/view.spec.ts
- js/src/app/view/view.ts
- js/src/personal/view/view.spec.ts
- js/src/personal/view/view.ts
- lib/AppInfo/Application.php
- lib/Db/OcrJobMapper.php
- lib/Hooks/UserHooks.php
- tests/Unit/AppInfo/ApplicationTest.php
- tests/Unit/Db/OcrJobMapperTest.php
- tests/Unit/Hooks/UserHooksTest.php
- worker/src/worker.ts
> 94: Hook for user deletion and minor fixes

- CHANGELOG.md
- appinfo/database.xml
- appinfo/info.xml
- css/ocrpersonal.css
- css/ocrstyle.css
- js/dist/ocrapp.js
- js/dist/ocrpersonal.js
- js/src/app/controller/controller.spec.ts
- js/src/app/controller/controller.ts
- js/src/app/service/http.service.spec.ts
- js/src/app/service/http.service.ts
- js/src/app/view/templates/ocr.dropdown.hbs
- js/src/app/view/view.spec.ts
- js/src/app/view/view.ts
- js/src/personal/controller/poto/job.poto.ts
- js/src/personal/view/templates/ocr.status-table.hbs
- js/src/personal/view/view.spec.ts
- js/src/personal/view/view.ts
- lib/Controller/JobController.php
- lib/Db/OcrJob.php
- lib/Service/FileService.php
- lib/Service/JobService.php
- tests/Unit/Controller/JobControllerTest.php
- tests/Unit/Db/OcrJobTest.php
- tests/Unit/Service/FileServiceTest.php
- tests/Unit/Service/JobServiceTest.php
- worker/src/service/ocr-processing.service.spec.ts
- worker/src/service/ocr-processing.service.ts
> 54: Replacing original file by ocred one

- worker/Dockerfile
Update Dockerfile regarding LC_ALL / LANG
Fixes https://github.com/janis91/ocr/issues/126
https://github.com/janis91/ocr/issues/126
> Update Dockerfile regarding LC_ALL / LANG

- lib/Constants/OcrConstants.php
- lib/Settings/Admin.php
- lib/Settings/Section.php
- tests/Unit/Settings/SectionTest.php
> Added small fix regarding not displaying section icon

- css/ocrstyle.css
- js/src/app/controller/controller.ts
- js/src/app/view/view.spec.ts
- js/src/app/view/view.ts
> Added small fix regarding overlapping header row file actions

- js/src/app/view/View.ts
- js/test/app/view/View.spec.ts
> Changed text for replace option, to better fit the behavior.

- js/src/app/App.ts
- js/src/app/service/OcaService.ts
- js/src/app/service/TesseractService.ts
- js/test/app/App.integration.spec.ts
- js/test/app/service/TesseractService.spec.ts
> Added better resolution of worker and core script of tesseract.

- css/ocr.css
Fixes the weird behavior of shrinking input field when typing, that is build into choices.js.
> Added small override of width for the language input.

- js/src/app/App.ts
- js/src/app/util/Util.ts
- lib/AppInfo/Application.php
> Fix csp and js

- js/src/app/configuration/Configuration.ts
- js/src/app/controller/Controller.ts
- js/src/app/service/OcaService.ts
- js/src/app/service/PdfService.ts
- js/src/app/service/TesseractService.ts
- js/src/app/util/Util.ts
- js/src/app/view/View.ts
- js/test/app/controller/Controller.spec.ts
- js/test/app/view/View.spec.ts
> Centralized all translations in js, such that no translation strings are missed by transifex bot

- js/src/app/controller/Controller.ts
- js/src/app/service/OcaService.ts
- js/src/app/service/TesseractService.ts
- js/src/global-oc-types.ts
- js/test/app/controller/Controller.spec.ts
- js/test/app/service/OcaService.spec.ts
- js/test/app/service/TesseractService.spec.ts
Added reset round robin index in the project to save resources when creating workers and fixed deletion in sub path of original file.
Fixes #199 
Signed-off-by: Janis Köhr <janis.koehr@novatec-gmbh.de>
> Fixes deletion issue and saves up resources

- js/src/app/configuration/Configuration.ts
- js/test/app/view/View.spec.ts
Signed-off-by: Janis Köhr <janis.koehr@novatec-gmbh.de>
> Fixed typo, corresponding to #205.

- .vscode/settings.json
- js/package-lock.json
- js/package.json
- js/src/app/service/PdfService.ts
- js/test/app/service/PdfService.spec.ts
Fixes #207:
This adjustment provides a higher dpi for all pdfs that are output of the tesseract process.
> Adjusted pdf dpi to at least 300 (viewport scale).

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- js/src/app/service/TesseractService.ts
- js/test/app/service/TesseractService.spec.ts
> Adjusted to tesseract beta v12 and fixed the ocr process bug.

- .travis.yml
- README.md
- appinfo/info.xml
Tested with version 17 (beta3) of nextcloud and updated max-version correspondingly.
Signed-off-by: Janis Köhr <janis.koehr@novatec-gmbh.de>
> NC 17 release

- js/src/app/service/HttpService.ts
- js/src/global-oc-types.ts
- js/src/settings/service/HttpService.ts
- js/test/app/service/HttpService.spec.ts
- js/test/app/service/OcaService.spec.ts
- js/test/settings/service/HttpService.spec.ts
Fixed url generation for nextclouds that are not run under root and if the app is operated from non standard folder
Refactoring by unit tests and corresponding fixes.
> Fix webroot and non standard app folder issue

- js/src/app/App.ts
- js/src/settings/App.ts
Added comment to avoid false positive alert
> Avoid false positive alert

- css/app.css
- css/settings.css
- lib/Controller/PersonalSettingsController.php
- tests/Unit/Controller/PersonalSettingsControllerTest.php
Added dark theme support to the dialog, icon and everything else.
Fixes #215 
Manual test with dark mode and without.
> Added dark theme support

- .travis.yml
- .vscode/settings.json
- appinfo/info.xml
Added server occ util to deploy step for code signing and fixed some vscode settings
#219 
manually.
> Travis fix

- .travis.yml
Should fix the code singing step finally
#219
manually.
> Fixed travis code singing step

- .travis.yml
> Added travis code signing fix

- README.md
> Credited jeromewu for his ecellent work with tesseract-js

- README.md
- appinfo/info.xml
- appinfo/routes.php
- ci/build_release.sh
- ci/gitTag.js
- js/src/app/App.ts
- js/src/app/service/TesseractService.ts
- js/test/app/App.integration.spec.ts
- js/test/app/service/HttpService.spec.ts
- js/test/app/service/TesseractService.spec.ts
- lib/AppInfo/Application.php
- lib/Constants/OcrConstants.php
- lib/Controller/TessdataController.php
- lib/Migration/CleanupTessdata.php
- lib/Migration/DropOldTable.php
- lib/Migration/FetchTessdata.php
- lib/Service/TessdataService.php
- lib/Util/FetchTessdataUtil.php
- tests/Unit/Controller/TessdataControllerTest.php
- tests/Unit/Migration/CleanupTessdataTest.php
- tests/Unit/Migration/FetchTessdataTest.php
- tests/Unit/Service/TessdataServiceTest.php
> Changed tessdata loading behavior from remote to local

- appinfo/info.xml
> Set max version to 18

- lib/Migration/FetchTessdata.php
- tests/Unit/Migration/FetchTessdataTest.php
> Added specific timeout

- .github/CONTRIBUTING.md
- .gitignore
- LICENSE
- ci/build_release.sh
- lib/AppInfo/Application.php
- lib/Migration/FetchTessdata.php
- src/app/App.vue
- tests/Unit/Migration/FetchTessdataTest.php
Signed-off-by: Janis Köhr <janis.koehr@novatec-gmbh.de>
> Small fixes for repair step and other things.

- lib/Controller/TessdataController.php
> Added @NoAdminRequired

- appinfo/info.xml
- src/common/Common.ts
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Spelling unification

- src/app/configuration/Translations.ts
Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
> l10n: Fixed grammar
